package com.studentportal.security.aws;

public enum ResultReasons {
    FIELDS_INCOMPLETE,
    NOT_AUTHORIZED,
    NO_SUCH_USER,
    LOGGED_IN,
    TEMP_PASSWORD_USED,
    TOO_MANY_REQUESTS,
    EMAIL_EXISTS,
    REGISTER_CONFIRMED,
    VERIFICATION_CODE_SENT,
    RESET_CONFIRMED,
    INVALID_PASSWORD,
    TEMP_PASSWORD_SENT,
    CODE_DELIVERY_FAILED,
    INVALID_PARAMS,
    USER_NOT_CONFIRMED,
    VERIFICATION_CODE_MISMATCH,
    TOO_MANY_ATTEMPTS,
    EXPIRED_VERIFICATION_CODE
}
